### ISSUE TITLE
Player getting crash on entering server

### ISSUE THREAD

**Issue by Mad-Gnome** [Zflocco/Swordz#4]
VS 1.19.7
Swordz 1.1.7

Have 1 player when they try to join my server they are experiencing a crash every time they attempt to connect.  They've deleted their swordz config, swordz mod and cache folder.

What eventually fixed it was deleting their entire VintageStoryData folder, and then reinstalling.

System.Exception: Don't know how to instantiate block of class 'BlockFantasyMeteorite' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in VintagestoryLib\Common\ClassRegistry.cs:line 130
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 403
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\Startup.cs:line 553
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 370
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 345
   at Vintagestory.API.Common.TyronThreadPool.<>cDisplayClass12_0.<QueueTask>b0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Zflocco** [comment]
Was it just the one player, or is it making it unusable? 
Also, is that error code from the player, or every time from startup?

**Comment by Mad-Gnome** [comment]
I had 3 players who had issues when they updated from 1.1.6 to 1.1.7, but deleting the old ModConfig and Clearing their cache fixed it for 2 of them.
The third player had to delete their entire vintagestorydata folder, and then it worked fine for them.  Not sure what gremlin got into their install for it.

**Comment by Zflocco** [comment]
> I had 3 players who had issues when they updated from 1.1.6 to 1.1.7, but deleting the old ModConfig and Clearing their cache fixed it for 2 of them. The third player had to delete their entire vintagestorydata folder, and then it worked fine for them. Not sure what gremlin got into their install for it.

I find this rather strange, I haven't personally had any errors and neither has my server as a whole. You should be able to delete the Aithril meteorite worst comes to worst, I haven't been able to get that to work properly (obviously)

**Comment by Zflocco** [comment]
Fixed in 1.1.8
